db:
  image: postgres
web:
  build: .
  command: bundle exec rails server --binding 0.0.0.0
  ports:
    - "3000:3000"
  links:
    - db
  volumes:
    - .:/myapp
  environment:
    RACK_ENV: development
    RAILS_ENV: development
  env_file: .env
