##
## Postgres
##

- name: Create {{database_name}} database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{database_name}}

- name: Create user {{database_user}} on {{database_name}}
  sudo: yes
  sudo_user: postgres
  postgresql_user: db={{database_name}}
                   name={{database_user}}
                   password={{database_password}}
                   role_attr_flags=CREATEDB,SUPERUSER

##
## Rails
##

- name: mkdir -p ~{{deploy}}/apps/{{full_app_name}}/shared/config
  file: path=~{{deploy}}/apps/{{full_app_name}}/shared/config state=directory

- name: Copy database.yml to config
  sudo: yes   # or chgrp will fail. For some reason, the setgid doesn't work here.
  template: src=database.yml.j2 dest=~{{deploy}}/apps/{{full_app_name}}/shared/config/database.yml owner={{deploy}} group=www-data mode=0640

###
### Nginx
###

- name: Deploy {{full_app_name}} nginx config to sites-available
  sudo: yes
  template: src={{full_app_name}}.nginx.j2 dest=/etc/nginx/sites-enabled/{{full_app_name}}
  notify: restart_nginx
