---
- hosts: all
  user: "{{ root_user }}"
  sudo: yes
  gather_facts: no
  roles:
    - { role: create-deploy-user, tags: ['create-deploy-user'] }

- hosts: all
  remote_user: "{{ deploy }}"
  gather_facts: no
  roles:
    ### Server provisioning roles:
    - { role: linux-prereqs, tags: ['linux-prereqs'] }
    # - { role: ufw, tags: ['ufw'] }
    - { role: postgresql, tags: ['postgresql'] }
    - { role: rbenv, tags: ['rbenv'] }
    - { role: ruby, tags: ['ruby'] }
    # - { role: papertrail, tags: ['papertrail'] }
    - { role: nginx-passenger, tags: ['nginx-passenger'] }
    - { role: lets-encrypt, tags: ['letsencrypt'] }

    ### Site specific roles:
    - { role: prepare_site, tags: ['prepare_site'] }
    - { role: copy-env, tags: ['copy-env'] }
