

# python-pycurl is required for apt_key module
# see https://groups.google.com/forum/#!topic/ansible-project/ooAm8g3EEsU



# BUG: When running 'vagrant up' for the first time, the python-pycurl task
# always fails, with:
#
# msg: Failed to lock apt for exclusive operation
#
# The next time you run 'vagrant provision' it will be fine.
#
# Suspect race condition with the 'async' apt job run previous to this.
#
# Commenting this job out to see if it makes a difference.
# The package is already installed in linux-prereqs.

# - name: Install python-pycurl
#   apt: pkg=python-pycurl state=latest update_cache=true

# BUG: Is it secure to retrieve a PGP key over HTTP?
- name: Add PostgreSQL repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
  sudo: yes

- name: Add PostgreSQL repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
  sudo: yes

- name: Install postgresql, libpq-dev, python-psycopg2
  action: apt pkg={{item}} state=latest update_cache=true
  sudo: yes
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Copy valid pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.4/main/pg_hba.conf
  sudo: yes

- name: Copy .pgpass
  template:
    src: pgpass.j2
    dest: "~{{ deploy }}/.pgpass"
    mode: 0600

- name: Restart PostgreSQL
  # NOTE: If conf files were updated here, need to FORCE a RESTART!
  service: name=postgresql state=started
  sudo: yes
